create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  phone text,
  plan text,
  paid boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  lesson_id int not null,
  completed boolean default false,
  score int default 0,
  updated_at timestamptz default now(),
  unique(user_id, lesson_id)
);

alter table public.profiles enable row level security;
alter table public.lesson_progress enable row level security;

create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);

create policy "Users can read own progress" on public.lesson_progress for select using (auth.uid() = user_id);
create policy "Users can insert own progress" on public.lesson_progress for insert with check (auth.uid() = user_id);
create policy "Users can update own progress" on public.lesson_progress for update using (auth.uid() = user_id);
